[workspace]
resolver = "2"
members = ["beancount-parser-lima", "beancount-parser-lima-python"]

[workspace.dependencies]
lazy_format = "2.0.3"
rust_decimal = "1.36.0"
smallvec = "2.0.0-alpha.10"
strum = "0.27.1"
strum_macros = "0.27.1"
time = "0.3.37"
