[package]
name = "beancount-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.25"
either = "1.8.1"
itertools = "0.10.5"
nom = { version = "7.1.3", features = ["alloc"] }
nom-supreme = "0.8.0"

[dev-dependencies]
anyhow = "1.0.71"
test-case = "3.1.0"
