[package]
name = "beancount-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
ariadne = "0.3.0"
chrono = "0.4.25"
chumsky = { version = "1.0.0-alpha.4", features = ["label", "regex"] }
either = "1.8.1"
itertools = "0.10.5"
logos = "0.13.0"
nonempty = "0.8.1"
rust_decimal = "1.29.1"
strum = "0.25.0"
strum_macros = "0.25.0"

[dev-dependencies]
test-case = "3.1.0"
rust_decimal_macros = "1.29.1"
